services:
  - type: web
    name: hawkbeam-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NPM_CONFIG_PRODUCTION
        value: false
    staticPublishPath: ./frontend/dist
